steps:
  - id: "set build number from git push"
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git rev-parse --short HEAD > _BUILDNUMBER
    waitFor: ['-']

  - id: "build and deploy a dataflow job"
    name: 'gradle:7.5.1-jdk17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update
        apt-get install sudo
        sudo bash submit.sh org.example.Main \
          --project=macro-mercury-374220 \
          --stagingLocation=gs://big-data-files-1/staging/ \
          --gcpTempLocation=gs://big-data-files-1/temp/ \
          --runner=DataflowRunner \
          --buildNumber=${buildNumber} \
          --serviceAccount=full-access-role@macro-mercury-374220.iam.gserviceaccount.com \
          --jobName=cloudbuild-dataflowjob-1 \
          --numWorkers=2 \
          --maxNumWorkers=20 \
          --region=southamerica-east1 \
    waitFor: ['set build number from git push']
options:
  logging: CLOUD_LOGGING_ONLY

