steps:
  - id: "set build number from git push"
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git rev-parse --short HEAD > _BUILDNUMBER
    waitFor: ['-']
    options:
      logging: CLOUD_LOGGING_ONLY

  - id: "build and deploy a dataflow job"
    name: 'gradle:6.8.3-jdk11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        buildNumber=$(cat _BUILDNUMBER)
        echo "Build Number is ${buildNumber}"
        apt-get update
        apt-get install sudo
        sudo bash submit.sh org.example.Main \
          --project=macro-mercury-374220 \
          --stagingLocation=gs://gcp-dataflow-cloudbuild-stage/staging/ \
          --gcpTempLocation=gs://gcp-dataflow-cloudbuild-temp/temp/ \
          --runner=DataflowRunner \
          --buildNumber=${buildNumber} \
          --serviceAccount=full-access-role@macro-mercury-374220.iam.gserviceaccount.com \
          --jobName=cloudbuild-dataflowjob-1 \
          --numWorkers=2 \
          --maxNumWorkers=20 \
          --usePublicIps=false \
          --region=southamerica-east1 \
    waitFor: ['set build number from git push']

